update: change Update-time, Start-time, End-time in GOV
orai-us/scanium pull request #15
Opened 2024-11-11 03:53 UTC by ninhxuanhuan

2024-11-11 09:11 UTC, quanpt239 requested changes
@ninhxuanhuan check

2024-11-11 09:11 UTC, quanpt239 commented on src/components/contracts/TransactionContractIndexs.vue
> +    orderBy: "TIMESTAMP_DESC",
sort theo block number nhé, nó đc index

2024-11-11 09:11 UTC, quanpt239 commented on src/modules/[chain]/gov/[proposal_id].vue
> +    return (height - current) * 1000;
block time của mình trung bình đang là 0.89s nhé
https://scan.orai.io/

2024-11-11 09:29 UTC, ninhxuanhuan commented on src/modules/[chain]/gov/[proposal_id].vue
> +    return (height - current) * 1000;
chỗ này không phải block time anh ạ
nó là upgradeTime của Vote anh ạ

2024-11-12 12:06 UTC, quanpt239 approved these changes
LGTM

2024-11-12 12:06 UTC, merged